config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'todolists#index'

resources :todolists do 
	resources :items do 
		member do 
			patch :complete
		end 
	end 
end 
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
validates_presence_of :content
  belongs_to :todolist

  def completed?
  	!completed_at.blank?
  end 
end

app/models/todolist.rb
class Todolist < ApplicationRecord
	validates_presence_of :title, :description
	has_many :items, dependent: :destroy
	# if not dependent, when delete a list(with items in it), an error will occur
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :set_todolist
before_action :set_item, except: [:create]
# these two repeated a lot, so make them private and before action
#  except, so we dont call set_item on create action
	def create
		# @todolist = Todolist.find(params[:todolist_id])
		# make this a before_action
		@item = @todolist.items.create(item_params)
		redirect_to @todolist
	end 

	def destroy
		# @item = @todolist.items.find(params[:id])
		@item.destroy
		redirect_to todolist_path(@todolist)
	end 

	def complete
		@item.update_attribute(:completed_at, Time.now)

		redirect_to @todolist, notice: 'to do item completed'
	end 




	private

	def set_todolist
		@todolist = Todolist.find(params[:todolist_id])
	end 

	def set_item
		@item = @todolist.items.find(params[:id])
	end 

	def item_params
		params[:item].permit(:content)
	end 

end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController

	def index
	  @todolists = Todolist.all
	end 

	def new 
	  @todolist = Todolist.new
	end 
# edit function usually between new and create
    def edit
		@todolist = Todolist.find(params[:id])
	end

	def create 
		# render plain: params[:todolist].inspect
	  @todolist = Todolist.new(todolist_params)
	  @todolist.save
	  if  @todolist.save
        # render json: {saved: true}
       redirect_to @todolist
      else
        # render json: {saved: false, errors:  @todolist.errors.full_messages}
        render 'new'
      end

	end 

   def update
   	  @todolist = Todolist.find(params[:id])

   	   if @todolist.update(todolist_params)
		   redirect_to @todolist
	   else
		   render 'edit'
	   end
   end 


	def show
		@todolist = Todolist.find(params[:id])
	end 

	def destroy
		@todolist = Todolist.find(params[:id])
		@todolist.destroy
		redirect_to todolists_path
	end 

 


    private

    def todolist_params
    	params.require(:todolist).permit(:title, :description)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/items/_form.html.erb
  <%= form_for ([@todolist, @todolist.items.build]) do |f|%>
    <p>
    	<%= f.text_field :content%>
    </p>
    <p>
    	<%= f.submit%>
    </p>
  <%end%>

app/views/items/_item.html.erb
<div class="row clearfix">
  <% if item.completed? %>
    <div class="complete">
      <%= link_to complete_todolist_item_path(@todolist, item.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="item">
      <p style="opacity: 0.4;"><strike><%= item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to todolist_item_path(@todolist, item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_todolist_item_path(@todolist, item.id), method: :patch do %>
        <i class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="item">
      <p><%= item.content %></p>
    </div>
    <div class="trash">
      <%= link_to todolist_item_path(@todolist, item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>

 <div class="container">
 	<%= yield %>
 </div>
    
  </body>
</html>

app/views/todolists/_form.html.erb
<%=form_for :todolist, url: todolists_path do |f|%>

  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todolist.errors.count, "error") %> prohibited
        this todolist from being saved:
      </h2>
      <ul>
        <% @todolist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
 
  	<%= f.label :title%><br>
  	<%= f.text_field :title %>
  </div>  

  <div class="field">
  	<%= f.label :description%><br>
  	<%= f.text_area :description %>
  </div>

  <div class="action">
  	<%= f.submit%>
  </div>

<% end %>

app/views/todolists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>
<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
  <%=link_to 'cancel', todolists_path%>
</div>

app/views/todolists/index.html.erb
<% @todolists.each do |todolist| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to todolist.title, todolist %></h2>
    <p class="todo_list_sub_title"><%= todolist.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Todo List", new_todolist_path %>
</div>

<!-- show page: add link to title, todolist -->
<!-- after styling no edit or delete showed here -->

<!--
<h1>This is todolist index page</h1>


<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
 
  <% @todolists.each do |todolist| %>
    <tr>
      <td><%= todolist.title %></td>
      <td><%= todolist.description %></td>
      <td><%= link_to 'Show', todolist_path(todolist) %></td>
      <td><%= link_to 'edit', edit_todolist_path(todolist) %></td>
      <td><%= link_to 'delete', todolist_path(todolist),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
-->

app/views/todolists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', todolists_path %>
</div>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="todo_list_title"><%= @todolist.title %></h2>
<p class="todo_list_sub_title"><%= @todolist.description %></p>


<div id="todo_items_wrapper">
 
 
    <%= render @todolist.items%>
 
    <div id="form">
      <%=render 'items/form'%>
    </div>
</div>


<div class="links">
  <%= link_to 'Edit', edit_todolist_path(@todolist) %>|
  <%= link_to 'Delete', todolist_path(@todolist),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>|
  <%= link_to 'Back', todolists_path%>
</div>